CREATE DATABASE TRIMESTRAL3;
USE TRIMESTRAL3;

CREATE TABLE CLIENTES(
	CODIGO INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL,
    TELEFONE VARCHAR(200) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL
)ENGINE=INNODB;